-- Seed massivo: adiciona 22 templates Blotato ao catalogo (somam aos 13 ja seedados = 35 total).
-- 17 infograficos (inputs uniformes: description + footerText), 5 templates especiais (carrosseis,
-- slideshows, single-quote, product-placement) com schemas customizados.
--
-- Templates AI video (ai-story-video, ai-selfie-video, ai-avatar-broll, combine-clips) NAO incluidos
-- nesta migration - custo alto e formato diferente, ficam pra Fase 4.
--
-- preview_url: placeholder. Raul atualiza com screenshots reais depois.
-- viral_views: estimativas baseadas nos prints; nulls onde sem dado.

INSERT INTO public.templates
  (slug, name, description, category, format, aspect_ratios, preview_url, engine, blotato_template_id, prompt_template, input_schema, cost_credits, viral_views, brand_slots)
VALUES
  ('tv-wall-infographic',
   'TV Wall',
   'Layout de parede de TVs com varias telas. Otimo pra anuncios e launches.',
   'infographic', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/tv-wall.png',
   'blotato', '013904bf-6b3b-43f4-bb1f-f1964a38c29b', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1500000, NULL),

  ('trail-marker-infographic',
   'Trail Marker',
   'Placa de trilha na natureza com texto incrustado. Estetica diferente, alta retencao.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/trail-marker.png',
   'blotato', '29ebb2bd-02b7-4317-8bb8-c30eb938e47c', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1300000, NULL),

  ('graffiti-mural-infographic',
   'Graffiti Mural',
   'Mural de grafite urbano com mensagem. Visual jovem e impactante.',
   'infographic', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/graffiti.png',
   'blotato', '3598483b-c148-4276-a800-eede85c1c62f', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1500000, NULL),

  ('tshirt-infographic',
   'T-Shirt',
   'Texto estampado em camiseta - mensagem em contexto de moda.',
   'infographic', 'post', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/tshirt.png',
   'blotato', '476f8920-8749-4ff7-9c91-470d54c3c03e', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":600},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1100000, NULL),

  ('constellation-infographic',
   'Constellation',
   'Constelacao com texto em pontos conectados. Visual cosmico e cientifico.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/constellation.png',
   'blotato', '5307053e-046b-4c9b-b1ca-38725d2ddcdd', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1500000, NULL),

  ('steampunk-infographic',
   'Steampunk',
   'Estetica steampunk com engrenagens e texto vintage.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/steampunk.png',
   'blotato', '7b7104f1-d277-4993-ad3a-e5883c4b776d', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 800000, NULL),

  ('cave-painting-infographic',
   'Cave Painting',
   'Pintura rupestre em parede de caverna. Estilo primitivo memoravel.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/cave-painting.png',
   'blotato', '82ee75b6-597b-43a8-86bc-e4395e7c9c44', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 700000, NULL),

  ('futuristic-flyer-infographic',
   'Futuristic Flyer',
   'Flyer futurista com gradientes e neons. Ideal pra tech e gaming.',
   'infographic', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/futuristic-flyer.png',
   'blotato', '8fa8545e-8955-4a89-a868-cf45023d6cc5', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 900000, NULL),

  ('egyptian-hieroglyph-infographic',
   'Egyptian Hieroglyph',
   'Hieroglifos egipcios em pedra antiga. Visual mitico e atemporal.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/egyptian.png',
   'blotato', 'a7b0d128-8478-4b34-9647-a0778b6517d0', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 800000, NULL),

  ('top-secret-infographic',
   'Top Secret',
   'Documento confidencial rasurado com aparencia de declassified. 1.3M views no Blotato.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/top-secret.png',
   'blotato', 'b8707b58-a106-44af-bb12-e30507e561af', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1300000, NULL),

  ('book-page-infographic',
   'Book Page',
   'Pagina de livro antigo com paragrafo destacado. Otimo pra citacoes e dicas.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/book-page.png',
   'blotato', 'b88c8273-6406-48c6-85e7-096119aefe30', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 600000, NULL),

  ('classroom-chalkboard-infographic',
   'Classroom Chalkboard',
   'Quadro-negro de sala de aula com guia escrito a giz.',
   'infographic', 'post', ARRAY['4:5'],
   'https://placeholder.trendpulse.com.br/classroom-chalkboard.png',
   'blotato', 'd9495026-3945-44f6-8b44-07c28c492e6d', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1100000, NULL),

  ('movie-theater-infographic',
   'Movie Theater',
   'Tela de cinema com texto projetado. Visual cinematografico.',
   'infographic', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/movie-theater.png',
   'blotato', 'f8f1ebe4-a9f5-4ec8-be63-21214656cd4b', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Tema do post","required":true,"max":1000},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1500000, NULL),

  ('bus-ad-infographic',
   'Bus Ad',
   'Anuncio em onibus urbano - formato horizontal de outdoor movel.',
   'infographic', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/bus-ad.png',
   'blotato', 'f9c0e470-9288-4958-8cdd-64772ed93c05', NULL,
   '{"fields":[{"name":"description","type":"textarea","label":"Mensagem","required":true,"max":300},{"name":"footerText","type":"text","label":"Rodape","required":false,"max":120}]}'::jsonb,
   1, 1500000, NULL),

  ('single-centered-quote',
   'Single Centered Quote',
   'Citacao unica centralizada em fundo limpo. Minimalismo puro.',
   'card', 'post', ARRAY['1:1'],
   'https://placeholder.trendpulse.com.br/single-quote.png',
   'blotato', '9f4e66cd-b784-4c02-b2ce-e6d0765fd4c0', NULL,
   '{"fields":[{"name":"quotes","type":"array","item_type":"textarea","label":"Citacao","required":true}]}'::jsonb,
   0, 200000, ARRAY['accent_color']),

  ('quote-mono-card',
   'Quote Card Monocolor',
   'Quote card carrossel com paper background monocromatico. Free.',
   'carousel', 'carousel', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/quote-mono.png',
   'blotato', '/base/v2/quote-card/77f65d2b-48cc-4adb-bfbb-5bc86f8c01bd/v1', NULL,
   '{"fields":[{"name":"title","type":"text","label":"Titulo","required":true,"max":80},{"name":"quotes","type":"array","item_type":"textarea","label":"Quotes","required":true}]}'::jsonb,
   0, 150000, ARRAY['accent_color']),

  ('tutorial-carousel-flat',
   'Tutorial Carousel Flat',
   'Carrossel tutorial estilo minimalista flat com perfil + CTA.',
   'carousel', 'carousel', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/tutorial-flat.png',
   'blotato', '/base/v2/tutorial-carousel/2491f97b-1b47-4efa-8b96-8c651fa7b3d5/v1', NULL,
   '{"fields":[{"name":"mainTitle","type":"text","label":"Titulo principal","required":true,"max":80},{"name":"contentItems","type":"array","item_type":"textarea","label":"Itens","required":true},{"name":"authorName","type":"text","label":"Autor","required":true},{"name":"profileImage","type":"image","label":"Foto perfil URL","required":false}]}'::jsonb,
   0, 600000, ARRAY['profileImage','accentColor']),

  ('image-slideshow-prominent',
   'Image Slideshow Prominent Text',
   'Slideshow de imagens com texto extra-grande em destaque.',
   'slideshow', 'post', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/slideshow-prominent.png',
   'blotato', '/base/v2/images-with-text/0ddb8655-c3da-43da-9f7d-be1915ca7818/v1', NULL,
   '{"fields":[{"name":"slides","type":"array","item_type":"textarea","label":"Texto por slide","required":true}]}'::jsonb,
   2, 2700000, NULL),

  ('when-x-then-y-slideshow',
   'When X then Y Slideshow',
   'Slideshow comparativo: situacao X vs resultado Y. 2.7M views no Blotato.',
   'slideshow', 'post', ARRAY['4:5','1:1'],
   'https://placeholder.trendpulse.com.br/when-x-then-y.png',
   'blotato', '/base/v2/images-with-text/c9892c3b-fa75-4ade-821a-a50ff8456230/v1', NULL,
   '{"fields":[{"name":"firstSlideText","type":"textarea","label":"Texto primeiro slide (X)","required":true,"max":200},{"name":"comparisonTextTop","type":"text","label":"Texto comparativo topo","required":false,"max":80},{"name":"comparisonTextBottom","type":"text","label":"Texto comparativo base","required":false,"max":80},{"name":"lastSlideText","type":"textarea","label":"Texto ultimo slide (Y)","required":true,"max":200}]}'::jsonb,
   2, 2700000, NULL),

  ('video-images-text-minimal',
   'Video of Images and Text Minimal',
   'Video curto de imagens com titulos e textos sobrepostos em estilo minimalista.',
   'slideshow', 'video', ARRAY['9:16','1:1'],
   'https://placeholder.trendpulse.com.br/video-minimal.png',
   'blotato', '/base/v2/images-with-text/3ed4bb92-dbfe-45e6-9dc8-605b77f70506/v1', NULL,
   '{"fields":[{"name":"titles","type":"array","item_type":"text","label":"Titulos por slide","required":true},{"name":"texts","type":"array","item_type":"textarea","label":"Textos por slide","required":true}]}'::jsonb,
   3, NULL, NULL),

  ('instagram-carousel-slideshow',
   'Instagram Carousel Slideshow',
   'Carrossel Instagram com slides gerados por IA a partir de prompts. 170K views.',
   'slideshow', 'carousel', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/instagram-carousel.png',
   'blotato', '53cfec04-2500-41cf-8cc1-ba670d2c341a', NULL,
   '{"fields":[{"name":"slidePrompts","type":"array","item_type":"textarea","label":"Prompt por slide","required":true}]}'::jsonb,
   3, 170000, NULL),

  ('product-scene-placement',
   'Product Scene Placement',
   'Coloca foto do seu produto numa cena gerada por IA (ex: estudio, ambiente real). 245K views.',
   'photo_quote', 'post', ARRAY['1:1','4:5'],
   'https://placeholder.trendpulse.com.br/product-placement.png',
   'blotato', 'f524614b-ba01-448c-967a-ce518c52a700', NULL,
   '{"fields":[{"name":"productImage","type":"image","label":"URL da foto do produto","required":true},{"name":"sceneDescription","type":"textarea","label":"Descricao da cena","required":true,"max":300}]}'::jsonb,
   2, 245000, NULL)
ON CONFLICT (slug) DO NOTHING;
